FROM mysql:8.0-debian@sha256:707f5c087531fde2fe4cd0fa3a125c7467e99b7f6282a3e6ed338604aedb8c25

# netcat is used to listen to the ports.

RUN apt-get -q update \
    && apt-get -q --yes install netcat-traditional pkg-config \
    && apt-get clean

# Lower error logging to get rid of health check spam
RUN ["/bin/bash", "-c", "echo '[mysqld]\nlog_error_verbosity=2' > /etc/mysql/conf.d/errors.cnf"]
